# Generated by Django 5.0.14 on 2026-02-16 14:21

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Сумма выплаты",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "Российский рубль"), ("USD", "Доллар США"), ("EUR", "Евро")],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "recipient_details",
                    models.JSONField(
                        help_text='Пример: {"card_number": "1234...", "account_id": "408..."}',
                        verbose_name="Реквизиты получателя",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("processing", "В обработке"),
                            ("success", "Выполнена"),
                            ("failed", "Ошибка"),
                            ("canceled", "Отменена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=255, null=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Выплата",
                "verbose_name_plural": "Выплаты",
                "ordering": ["-created_at"],
            },
        ),
    ]
